name: NewBasicTS
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.6.2=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.12.0=pyh08f2357_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.13=h2bbff1b_2
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py39haa95532_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.46=pyha770c72_0
  - prompt_toolkit=3.0.46=hd8ed1ab_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.9.18=h1aa4202_0
  - python_abi=3.9=2_cp39
  - pywin32=305=py39h2bbff1b_0
  - pyzmq=25.1.2=py39hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb82d6ee_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.1=pyha770c72_0
  - tzdata=2023d=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py39haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - argcomplete==3.2.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - boto==2.49.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - clarabel==0.6.0
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - crcmod==1.7
      - cryptography==41.0.7
      - cvxpy==1.4.1
      - cycler==0.12.1
      - easy-torch==1.3.2
      - easydict==1.10
      - ecos==2.0.12
      - fasteners==0.19
      - filelock==3.15.4
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gcs-oauth2-boto-plugin==3.0
      - google-apitools==0.5.32
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - google-reauth==0.1.1
      - grpcio==1.60.0
      - gsutil==5.27
      - gym==0.26.2
      - gym-notices==0.0.8
      - httplib2==0.20.4
      - huggingface-hub==0.24.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - learn2learn==0.2.0
      - markdown==3.5.2
      - markupsafe==2.1.3
      - matplotlib==3.9.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - numexpr==2.8.8
      - numpy==1.26.4
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - osqp==0.6.3
      - packaging==23.1
      - pandas==1.3.5
      - pillow==10.2.0
      - positional-encodings==6.0.3
      - protobuf==4.23.4
      - psutil==5.9.7
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycparser==2.21
      - pyopenssl==23.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyu2f==0.1.5
      - pyyaml==6.0.1
      - qdldl==0.1.7.post0
      - qpth==0.0.16
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - retry-decorator==1.1.1
      - rsa==4.7.2
      - safetensors==0.4.3
      - scikit-learn==1.0.2
      - scipy==1.13.1
      - scs==3.2.4.post1
      - setproctitle==1.3.2
      - setuptools==59.5.0
      - sympy==1.10.1
      - tables==3.7.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - timm==1.0.7
      - torch==1.10.0+cpu
      - torch-geometric==2.4.0
      - torchaudio==0.10.0+cu113
      - torchinfo==1.8.0
      - torchvision==0.11.0+cpu
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - yarl==1.9.4
prefix: C:\Anaconda3\envs\NewBasicTS
